version: "2"
services: 
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: unless-stopped
    ports: 
      - ${DECWPORT}:80
      - ${DECVNZPORT}:5900
    volumes:
      - ${DECDATA}:/opt/deCONZ
    devices:
      - ${DECDEV}
    environment:
      - TZ=${DECTZ}
      - DECONZ_WEB_PORT=80
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=${VNCPASS}
      - DECONZ_UID=${DECUID}
      - DECONZ_GID=${DECGID}
      - DECONZ_START_VERBOSE=0
volumes:
  decdata: