---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${SABCONF}:/config
    ports:
      - 9095:8080
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${RADCONF}:/config
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${SONCONF}:/config
    ports:
      - 8989:8989
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${LIDCONF}:/config
    ports:
      - 8686:8686
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${PROCONF}:/config
    ports:
      - 9696:9696
    restart: unless-stopped