version: '3'
services:
    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        volumes:
            - ${KAVCONF}:/kavita/config
        ports:
            - ${KAVPORT}:5000
        restart: unless-stopped
volumes:
  kavaconf: