---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - TZ=$DUPTIMEZONE
    volumes:
      - $DUPCONFDIR:/config
      - $DUPBKPDIR:/backups
      - $DUPSRCDIR:/source
    ports:
      - $DUPPORT:8200
    restart: unless-stopped
volumes:
    dupconf:
    dupbkp:
    dupsrc: